### ISSUE TITLE
Algunas cositas para mejorar

### ISSUE THREAD

**Issue by walterortizz** [giulianaerro/e-commerce-api#1]
Hola Giuli, cómo estás?. Te cuento estuve mirando el desafío y encontré algunas cosas a mejorar, dentro de todo la api funciona, pero a veces con inputs fuera de lo normal falla en algunas cuestiones, algunos ejemplos.

**1_** En el primer **endpoint (auth)** al no ingresar un email la api da un código de estado 500, esto se debe a una falla interna de la api, estaría bueno que al no recibir email devuelva un estado 400 por ejemplo, lo que causa el error es la **variable** que obtiene el email desde el **body** (linea 14)
![err1](https://user-images.githubusercontent.com/80477967/198896552-3eaa1a52-9115-4868-bdf9-0cf24c1e8e16.png)
 ya que debería estar dentro del try, así cuando da el error por no encontrar el email, este entraría directamente en el catch.

(_Por lo que pude ver, solo te olvidaste de agregar las variable dentro del try, porque en los demás endpoint lo tenés bien hecho_)

---------------------------------------------------------------------------------------------------------------------------------------------------

**2_**  Estuve mirando el archivo **token.ts** que se encuentra en **api/auth/**.
![err2](https://user-images.githubusercontent.com/80477967/198896695-b05ade37-7c4e-463b-ba25-153075781a62.png)
Y encontré un problema con las respuestas, ya que si llegase a ingresar primero en el if, y enviase
la respuesta con estado 404 **(linea 20)**, luego debajo volvería a enviar otra respuesta con el token, esto sucede porque al responder no se termina el proceso,
y así envía otra respuesta **(linea 25)**, lo correcto sería realizar un throw en el if, un return que no retorne nada o hacer un else luego del if.

También al llamar al endpoint y no pasarle un email o código este devuelve un código de estado 500, ocurre el mismo problema en el cual la **variable** que recibe  el email y el código da un error, para solucionarlo debería estar dentro del try, así cuando surja el error el catch pueda recibirlo.
(_Por lo que pude ver, solo te olvidaste de agregar las variable dentro del try, porque en los demás endpoint lo tenés bien hecho_)

---------------------------------------------------------------------------------------------------------------------------------------------------

**3_** En la función authMiddleware, ocurre nuevamente un error en las respuestas.
![err3](https://user-images.githubusercontent.com/80477967/198896943-b32e81a0-09d4-46a4-8340-943c422facd2.png)
Una solución sencilla podría ser dentro del primer if **(linea 9)** luego de responder el estado 401, sería
hacer un return, así evitas que se ejecute lo demás.

---------------------------------------------------------------------------------------------------------------------------------------------------

**4_** En el endpoint search, me parece que quedaría más bueno mover la llamada a **algolia search**, a un **controller**, así le bajas la responsabilidad al endpoint. 
![err4](https://user-images.githubusercontent.com/80477967/198897173-a28222f1-e22f-4264-afa3-90fb215e4add.png)
Luego también al buscar **req.query.search** (**linea 9**) para pasarlo al buscador de **algolia**, me da undefined, ya que la llamada al endpoint se hace con la **query** de busqueda q, como la documentación de postman lo indica, entonces lo correcto debería ser **req.query.q**

---------------------------------------------------------------------------------------------------------------------------------------------------

**5_** Por último al realizar la compra, luego de pagar, el estado de la orden no se me cambia a **closed**, se mantiene en **pending**, además tampoco me llega el email de confirmación de la compra, esta vez no pude corroborar y no podría decirte por donde iría el problema o si es un error mío.

---------------------------------------------------------------------------------------------------------------------------------------------------

Espero que te haya sido de ayuda el issue, voy a dar el desafío como aprobado porque dentro de todo se pudieron completar las pruebas, lo único que realmente falló fue lo de **cambiar la orden a "paid" o "closed"** y lo de la **query de busqueda en algolia search**, por lo demás sólo serían mejoras, sin más que agregar me despido y suerte!

**Comment by giulianaerro** [comment]
Graciasssss @walterARG2K ! muy buen feedback, ya arregle todo, cualquier cosita me avisas ? graciasss
